name: GitHub Actions Demo
on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Delete any existing file
        run: rm -f hello-world.txt
      - run: echo HelloFromAction > hello-world.txt
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: actions/upload-artifact@v3
        with:
          name: hello-world.txt
          path: hello-world.txt
  download:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - uses: actions/download-artifact@v3
        with:
          name: hello-world.txt
      - name: Display structure of downloaded files
        run: ls -R
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: cat hello-world.txt
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "hello world"
